### PR TITLE
Here is some important data

### PR DESCRIPTION
**Pull request by rokrbc**
Here you go

### CODE REVIEW

**Comment by lushep** [comment]
Hi Rokas, can you change the name of the folder to `names/`?

**Comment by rokrbc** [comment]
cannot find where required editor is...

**Comment by lushep** [comment]
> cannot find where required editor is...

Can you explain the problem a bit further?

**Comment by rokrbc** [comment]
Don't know the proper way to change the folder name in other words

**Comment by lushep** [comment]
You can right-click the folder and click rename. 

Or you can use the command:
`mv <old_folder_name> <new_folder_name>`

**Pull request closed without merging**
